import * as React from 'react';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
import { Button, CardActionArea, CardActions } from '@mui/material';
import HighlightDataService from '../../../assets/HighlightDataService.png';
import ScenariosAsAService from '../../../assets/ScenariosAsAService.png';
import PandemicScenarios from '../../../assets/PandemicScenarios.png';
import './services.scss';

const Services: React.FC = () => {  
return (    
    <Card style={{ display:'flex',  marginTop: '45px', marginLeft: '260px', gap: '28px', border:'none', width:1114, boxShadow: 'none', overflow:'visible'}}>
      <Card sx={{ width: 328, maxHeight: '363px', background: '#FAFDFF',
boxShadow: '0px 2px 2px rgba(4, 56, 84, 0.14), 0px 2px 3px rgba(4, 56 84, 0.12), 1px 2px 3px rgba(4, 56, 84, 0.2)',
borderRadius: '4px' }}>
      <CardActionArea sx={{
     '&:hover, &:focus': {
      color: '#FAFDFF',
      cursor: "default"
      }
  }}>
        <CardMedia
          component="img"
          height="140"
          image={HighlightDataService}
          alt="api"
        />
        <CardContent style={{padding:16}}>
          <Typography gutterBottom variant="h6" component="div" align="left" lineHeight='16px'>
            Highlight on Data Service    
        
           <button style={{backgroundColor: '#DA3232', color:'white', border:'none', fontSize: '10px', borderRadius: '4px', padding: '4px 6px 6px 6px', height:'36px', width:'61px', float:'right',
}}><p>NEW</p>
            </button>
          </Typography>
          <br></br> <br></br>
          <Typography variant="body2" textAlign= 'left'>
            My SS&C Data  is a modern data platform that puts the power of your relationship with SS&C to work. Users can tap in all the sources of their financial data hosted and generated by SS&C.
            <br></br>
          </Typography>
      <CardActions style={{ float: 'right'}}>
        <Button size="small" style={{color:'#2EACD4'}}>
          Learn More &#62;&#62;
        </Button>
      </CardActions>
        </CardContent>
      </CardActionArea>
    </Card>

    <Card sx={{ width: 328, maxHeight: '363px', background: '#FAFDFF',
boxShadow: '0px 2px 2px rgba(4, 56, 84, 0.14), 0px 2px 3px rgba(4, 56, 84, 0.12), 1px 2px 3px rgba(4, 56, 84, 0.2)',
borderRadius: '4px' }}>
      <CardActionArea>
        <CardMedia
          component="img"
          height="140"
          image={ScenariosAsAService}
          alt="algorithmics"
        />
         <CardContent style={{padding:16}}>
          <Typography gutterBottom variant="h6" component="div" align="left" lineHeight='24px'>
            Free Trial for Scenarios-as-a-Service
          </Typography>
   
          <Typography variant="body2" textAlign= 'left'>
            Algorithmics Scenarios-as-a-service  (ScaaS) is a subscription-based risk scenario and stimulation service. Take advantage of this free trial to see how ScaaS can help you assess and manage future risk.
          </Typography>
          <CardActions style={{float: 'right'}}>
            <Button size="small" style={{color:'#2EACD4'}}>
              Start your free trial &#62;&#62;
            </Button>
          </CardActions>
        </CardContent>
      </CardActionArea>
    </Card>

    <Card sx={{ width: 328, maxHeight: '363px', background: '#FAFDFF',
boxShadow: '0px 2px 2px rgba(4, 56, 84, 0.14), 0px 2px 3px rgba(4, 56, 84, 0.12), 1px 2px 3px rgba(4, 56, 84, 0.2)',
borderRadius: '4px' }}>
      <CardActionArea>
        <CardMedia
          component="img"
          height="140"
          image={PandemicScenarios}
          alt="pandemic"
        />
         <CardContent style={{padding:16}}>
          <Typography gutterBottom variant="h6" component="div" align="left" lineHeight='24px'>
            SS&C Algorithmics Pandemic Scenarios
          </Typography>
       
          <Typography variant="body2" textAlign= 'left'>
            How might the COVID-19 Pandemic affect your portofolio? We apply machine learning to understand how changes in case and illness statics might affect markets.
            <br></br><br></br></Typography>
          <CardActions style={{ float: 'right'}}>
            <Button size="small" style={{color:'#2EACD4'}}>
              View a live demo&#62;&#62;
            </Button>
          </CardActions>
        </CardContent>
      </CardActionArea>
    </Card>
    </Card>
);
};

export default Services;